name = "koffie-date"
main = "./build/index.js"
compatibility_date = "2024-10-07"
compatibility_flags = ["nodejs_compat"]

routes = [
  { pattern = "koffie.date", custom_domain = true }
]

[site]
  bucket = "./public"

[vars]
CALLS_APP_ID = "5eb135c01d5008c89bbff70043102465"
TURN_SERVICE_ID = "c31ec010c26b4ff56bd32d8742f18458"

[[durable_objects.bindings]]
name = "rooms"
class_name = "ChatRoom"

[[migrations]]
tag = "v1"
new_classes = ["ChatRoom", "RateLimiter"]
